# Generated from tooling/module.json; do not resolve stale global providers.
if(NOT CMAKE_PREFIX_PATH)
  set(CMAKE_PREFIX_PATH "${CMAKE_SOURCE_DIR}/build/deps/prefix")
endif()
find_path(_tooling_HoloNightConfig NAMES HoloNightConfigConfig.cmake PATHS ${CMAKE_PREFIX_PATH} PATH_SUFFIXES lib/cmake/HoloNightConfig lib64/cmake/HoloNightConfig share/HoloNightConfig/cmake NO_DEFAULT_PATH NO_CACHE)
if(NOT _tooling_HoloNightConfig)
  message(FATAL_ERROR "Missing HoloNightConfig in explicit CMAKE_PREFIX_PATH. Run task deps or supply a provider prefix.")
endif()
set(HoloNightConfig_DIR "${_tooling_HoloNightConfig}" CACHE PATH "Explicit local provider" FORCE)
find_path(_tooling_HolonightQt NAMES HolonightQtConfig.cmake PATHS ${CMAKE_PREFIX_PATH} PATH_SUFFIXES lib/cmake/HolonightQt lib64/cmake/HolonightQt share/HolonightQt/cmake NO_DEFAULT_PATH NO_CACHE)
if(NOT _tooling_HolonightQt)
  message(FATAL_ERROR "Missing HolonightQt in explicit CMAKE_PREFIX_PATH. Run task deps or supply a provider prefix.")
endif()
set(HolonightQt_DIR "${_tooling_HolonightQt}" CACHE PATH "Explicit local provider" FORCE)
find_path(_tooling_HolonightImages NAMES HolonightImagesConfig.cmake PATHS ${CMAKE_PREFIX_PATH} PATH_SUFFIXES lib/cmake/HolonightImages lib64/cmake/HolonightImages share/HolonightImages/cmake NO_DEFAULT_PATH NO_CACHE)
if(NOT _tooling_HolonightImages)
  message(FATAL_ERROR "Missing HolonightImages in explicit CMAKE_PREFIX_PATH. Run task deps or supply a provider prefix.")
endif()
set(HolonightImages_DIR "${_tooling_HolonightImages}" CACHE PATH "Explicit local provider" FORCE)
find_path(_tooling_HolonightThumbnails NAMES HolonightThumbnailsConfig.cmake PATHS ${CMAKE_PREFIX_PATH} PATH_SUFFIXES lib/cmake/HolonightThumbnails lib64/cmake/HolonightThumbnails share/HolonightThumbnails/cmake NO_DEFAULT_PATH NO_CACHE)
if(NOT _tooling_HolonightThumbnails)
  message(FATAL_ERROR "Missing HolonightThumbnails in explicit CMAKE_PREFIX_PATH. Run task deps or supply a provider prefix.")
endif()
set(HolonightThumbnails_DIR "${_tooling_HolonightThumbnails}" CACHE PATH "Explicit local provider" FORCE)
